### ISSUE TITLE
What does properties.experies_at mean ?

### ISSUE THREAD

**Issue by ThomasEcalle** [Purchasely/Purchasely-DemoFirebase#2]
Hi !

First of all, thank you for this extension that enables us, app developers, to win some time :)

I have recently implemented your Firebase extensions on one of my clients projects and I have one questions that I have in mind :

In your documentation, you say that, in order to retrieve users subscription, we should write something like that :

```
db.collection("PurchaselySubscriptions")
  .where("is_subscribed", "==", true)
  .whereField(
    "user.vendor_id",
    "==",
    "$CURRENT_USER_FIRESTORE_AUTHENTICATION_ID"
  )
  .get()
  .then(function (querySnapshot) {
    querySnapshot.forEach(async function (doc) {
      console.log(doc.id, " => ", doc.data());
    });
  });
  ```
  
But, when we look at the documents in the created collection (the `PurchaselySubscriptions` in my case), we also have other properties like the one that interests me : `properties.expires_at`

What is this property for ? 

I see that you don't take into account this property when filtering user subscriptions, but is not the expiration date of the subscription ?

Or do I have to "trust the process" and do not care about this property as maybe your extension will update the document when needed ?

Thanks in advance for your answer, I hope I made it clear but do not hesitate to ask for more details !

Have a great day/evening

**Comment by ste26054** [comment]
Hi Thomas!

Thanks for your question, I think you meant to publish on [this project](https://github.com/Purchasely/Purchasely-Firebase-Extension) (which is the actual Firebase Extension code), but I will answer to your question here :

`expires_at` corresponds to the time the subscription is due to expire, which will get pushed further in the future as renewal occurs. But in fact, as you said, you can completely trust the extension : if the subscription effectively expires, it will receive an event `DEACTIVATE` from Purchasely Webhook that expires and will remove the subscription from the Document.

As a general advice, sometimes the Stores do not update immediately the status of the subscription, so it is recommended to avoid expiring immediately if you were to rely just on an expiration timestamp.

**Comment by ThomasEcalle** [comment]
Hi @ste26054 

First of all, thanks a lot for your quick response and sorry for writing in the wrong channel !

I have now a better understanding of the utility of the `expires_at`.
I will trust the extension then ;)

Thanks again and have a great day !
